yarn.lock

fix(deps): recreated yarn.lock

---

generateTypes.js

fix(types): fixed generated types location

---

models/layerMetadata/layerMetadata.ts
yaml/layerMetadata.yaml

- added missing version filed (as required filed)
- added sourceName filed to the openApi model (as required filed)

fix: added version filed

---

yaml/layerMetadata.yaml

fix: fixed geometry ref

---

models/layerMetadata/layerMetadata.ts
yaml/layerMetadata.yaml

fix(yaml): yaml should match ts file definitions

---

src/yaml/layerMetadata.yaml

Tiff files yaml pattern

---

src/yaml/geojson.yaml

fix: change oneof to anyof due to validator limits

---

src/models/layerMetadata/index.ts

fix: publicly exported shape file types

---

src/models/layerMetadata/layer3DMetadata.ts
src/models/layerMetadata/pycsw3DCatalogRecord.ts

fix: rename relative le

---

src/models/layerMetadata/vectorBestMetadata.ts

vector raster best props fixes

fix: props fixes

---

src/yaml/3dCatalog/3dMetadata.yaml

In addition:
Updated footprint to Polygon

fix: limit arrays to contain a string

---

package-lock.json
package.json
src/yaml/insertLayerMetadata.yaml
src/yaml/updateLayerMetadata.yaml

extra commit for fixing start script

feat: Update date field not requierd

---

src/models/layerMetadata/pycsw3DCatalogRecord.ts

fix: insert date

---

package-lock.json
src/models/layerMetadata/decorators/property/tsTypes.decorator.ts
src/models/layerMetadata/enums.ts
src/models/layerMetadata/layerMetadata.ts
src/yaml/fullLayerMetadata.yaml
src/yaml/insertLayerMetadata.yaml
src/yaml/rasterCatalog/insertRequest.yaml

* transperancy records (transperant or opaque) -> profile for pycsw 
* tileFormatOutput - png or jpeg for raster internal uses of new ingestion

feat!: adding records entity for transparency + tileFormatOutput

---

package-lock.json
package.json
src/models/common/decorators/fieldConfig/fieldConfig.decorator.ts
src/models/common/decorators/graphQL/graphql.decorator.ts
src/models/layerMetadata/decorators/class/catalogDBEntity.decorator.ts
src/models/layerMetadata/decorators/property/catalogDB.decorator.ts
src/models/layerMetadata/decorators/property/csw.decorator.ts
src/models/layerMetadata/decorators/property/shp.decorator.ts
src/models/layerMetadata/decorators/property/tsTypes.decorator.ts
src/models/layerMetadata/enums.ts
src/models/layerMetadata/layerMetadata.ts
src/yaml/fullLayerMetadata.yaml
tsconfig.json

Adding new Catalog entity of Format -> associated with the image content type.

feat!: adding format column (image content type)

---

src/models/layerMetadata/layerMetadata.ts

tilesMimeFormat -> tileMimeFormat

fix: Update layerMetadata.ts

---

src/models/layerMetadata/layer3DMetadata.ts
src/yaml/3dCatalog/3dMetadata.yaml

3 more editable fields- startDate, endDate and footprint

3d profile changes

---

src/models/layerMetadata/layerMetadata.ts
src/models/layerMetadata/pycswLayerCatalogRecord.ts
src/models/raster/ingestion/ingestionTypes.ts
src/yaml/ingestionTrigger/metadata/rasterLayerMetadata.yaml
src/yaml/ingestionTrigger/partData/rasterLayerPartData.yaml
src/yaml/ingestionTrigger/rasterLayer.yaml
src/yaml/ingestionTrigger/rasterLayerExample.yaml

updated raster ingestion types for polygon parts.

fix: new raster ingestion modifications (MAPCO-4302)

---

src/models/layerMetadata/layerMetadata.ts
src/models/polygonParts/polygonPartRecord.ts
src/yaml/polygonPartsManager/payload.yaml
src/yaml/updateLayerMetadata.yaml

fix: product version regex pattern

---

src/models/layerMetadata/bestMetadata.ts
src/models/layerMetadata/layerMetadata.ts
src/models/polygonParts/polygonPartRecord.ts
src/models/raster/ingestion/types.ts
src/yaml/ingestionTrigger/metadata/rasterLayerMetadata.yaml
src/yaml/ingestionTrigger/rasterLayerExample.yaml
src/yaml/polygonPartsManager/payload.yaml
src/yaml/updateLayerMetadata.yaml

* renamed geometry to footprint in polygon parts context
* updated productId pattern validation
* styling

refactor: geometry to footprint and productId pattern validation

---

src/yaml/geojson.yaml

geojson examples

---

src/yaml/polygonPartsManager/payload.yaml

fix: schema should define partsData

---

src/models/layerMetadata/aggregatedLayerMetadata.ts

this adds aggregation layer metadata

feat: aggregation layer metadata

---

src/models/layerMetadata/index.ts
src/models/polygonParts/aggregationLayerMetadata.ts
src/models/polygonParts/index.ts
src/models/raster/ingestion/zod/schemas/partData.schema.ts
src/yaml/ingestionTrigger/partData/rasterLayerPartData.yaml

* fix openapi schema
* fix aggregation types
* update zod validations

refactor: aggregation

---

package-lock.json
src/yaml/3dCatalog/3dMetadata.yaml
src/yaml/geojsonWith3DPoints.yaml

* Add Support for 3D point in 3D ingestion
* Audit fix

feat: add support for point3D in 3D ingestion
